project:
  type: website
  output-dir: docs

website:
  title: "Pin's Website"
  site-url: "https://rsm-piw007.github.io/pw_personal_website"

  navbar:
    left:
      - href: index.qmd
        text: About
      - resume.qmd
      - href: blog.qmd
        text: Projects

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



